/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package net.danielthompson.danray.ui;

import net.danielthompson.danray.TraceManager;

/**
*
* @author daniel
*/
public class InfoJFrame extends javax.swing.JFrame {

   private TraceManager _traceManager;

   public void setMouseLocation(int x, int y) {
      screenXActualLabel.setText(x + "");
      screenYActualLabel.setText(y + "");
   }

   public void setSceneLocation(float x, float y, float z) {
      sceneXActualLabel.setText(String.format("%.2f", x));
      sceneYActualLabel.setText(String.format("%.2f", y));
      sceneZActualLabel.setText(String.format("%.2f", z));
   }

   public void setNoSceneLocation() {
      sceneXActualLabel.setText("N/A");
      sceneYActualLabel.setText("N/A");
      sceneZActualLabel.setText("N/A");
   }

   public void setCameraOrigin(float x, float y, float z) {
      originXActualLabel.setText(String.format("%.2f", x));
      originYActualLabel.setText(String.format("%.2f", y));
      originZActualLabel.setText(String.format("%.2f", z));
   }

   public void setCameraDirection(float x, float y, float z) {
      directionXActualLabel.setText(String.format("%.2f", x));
      directionYActualLabel.setText(String.format("%.2f", y));
      directionZActualLabel.setText(String.format("%.2f", z));
   }

   /**
   * Creates new form InfoJFrame
    * @param traceManager
    */
   public InfoJFrame(TraceManager traceManager) {
      _traceManager = traceManager;
      initComponents();
   }

   private final int MOVEMENT_AMOUNT = 20;

   private final int ROTATION_AMOUNT = 10;

   /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

     mouseJPanel = new javax.swing.JPanel();
     screenLabel = new javax.swing.JLabel();
     screenXLabel = new javax.swing.JLabel();
     screenXActualLabel = new javax.swing.JLabel();
     screenYLabel = new javax.swing.JLabel();
     screenYActualLabel = new javax.swing.JLabel();
     sceneLabel = new javax.swing.JLabel();
     sceneXLabel = new javax.swing.JLabel();
     sceneXActualLabel = new javax.swing.JLabel();
     sceneYLabel = new javax.swing.JLabel();
     sceneYActualLabel = new javax.swing.JLabel();
     sceneZLabel = new javax.swing.JLabel();
     sceneZActualLabel = new javax.swing.JLabel();
     cameraJPanel = new javax.swing.JPanel();
     originLabel = new javax.swing.JLabel();
     originXLabel = new javax.swing.JLabel();
     originXActualLabel = new javax.swing.JLabel();
     originYLabel = new javax.swing.JLabel();
     originYActualLabel = new javax.swing.JLabel();
     originZLabel = new javax.swing.JLabel();
     originZActualLabel = new javax.swing.JLabel();
     directionLabel = new javax.swing.JLabel();
     directionXLabel = new javax.swing.JLabel();
     directionXActualLabel = new javax.swing.JLabel();
     directionYLabel = new javax.swing.JLabel();
     directionYActualLabel = new javax.swing.JLabel();
     directionZLabel = new javax.swing.JLabel();
     directionZActualLabel = new javax.swing.JLabel();
     cameraOriginPanel = new javax.swing.JPanel();
     originAlongAxesPanel = new javax.swing.JPanel();
     originYPlusButton = new javax.swing.JButton();
     originZMinusButton = new javax.swing.JButton();
     originXMinusButton = new javax.swing.JButton();
     originXPlusButton = new javax.swing.JButton();
     originZPlusButton = new javax.swing.JButton();
     originYMinusButton = new javax.swing.JButton();
     originAlongOrientationPanel = new javax.swing.JPanel();
     originUpButton = new javax.swing.JButton();
     originForwardButton = new javax.swing.JButton();
     originLeftButton = new javax.swing.JButton();
     originRightButton = new javax.swing.JButton();
     originBackButton = new javax.swing.JButton();
     originDownButton = new javax.swing.JButton();
     cameraDirectionPanel = new javax.swing.JPanel();
     jPanel5 = new javax.swing.JPanel();
     directionYPlusButton = new javax.swing.JButton();
     directionZMinusButton = new javax.swing.JButton();
     directionXMinusButton = new javax.swing.JButton();
     directionXPlusButton = new javax.swing.JButton();
     directionZPlusButton = new javax.swing.JButton();
     directionYMinusButton = new javax.swing.JButton();
     jPanel6 = new javax.swing.JPanel();
     directionUpButton = new javax.swing.JButton();
     directionForwardButton = new javax.swing.JButton();
     directionLeftButton = new javax.swing.JButton();
     directionRightButton = new javax.swing.JButton();
     directionBackButton = new javax.swing.JButton();
     directionDownButton = new javax.swing.JButton();

     setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

     mouseJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mouse"));

     screenLabel.setText("Screen");

     screenXLabel.setText("X");

     screenXActualLabel.setText("jLabel3");

     screenYLabel.setText("Y");

     screenYActualLabel.setText("jLabel5");

     sceneLabel.setText("Scene");

     sceneXLabel.setText("X");

     sceneXActualLabel.setText("jLabel3");

     sceneYLabel.setText("Y");

     sceneYActualLabel.setText("jLabel5");

     sceneZLabel.setText("Z");

     sceneZActualLabel.setText("jLabel5");

     javax.swing.GroupLayout mouseJPanelLayout = new javax.swing.GroupLayout(mouseJPanel);
     mouseJPanel.setLayout(mouseJPanelLayout);
     mouseJPanelLayout.setHorizontalGroup(
         mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(mouseJPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(screenLabel)
             .addGap(18, 18, 18)
             .addComponent(screenXLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(screenXActualLabel)
             .addGap(18, 18, 18)
             .addComponent(screenYLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(screenYActualLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addComponent(sceneLabel)
             .addGap(18, 18, 18)
             .addComponent(sceneXLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(sceneXActualLabel)
             .addGap(18, 18, 18)
             .addComponent(sceneYLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(sceneYActualLabel)
             .addGap(18, 18, 18)
             .addComponent(sceneZLabel)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(sceneZActualLabel)
             .addContainerGap())
     );
     mouseJPanelLayout.setVerticalGroup(
         mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(mouseJPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                 .addGroup(mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(sceneZLabel)
                         .addComponent(sceneZActualLabel))
                     .addGroup(mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(sceneLabel)
                         .addComponent(sceneXLabel)
                         .addComponent(sceneXActualLabel)
                         .addComponent(sceneYLabel)
                         .addComponent(sceneYActualLabel)))
                 .addGroup(mouseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(screenLabel)
                     .addComponent(screenXLabel)
                     .addComponent(screenXActualLabel)
                     .addComponent(screenYLabel)
                     .addComponent(screenYActualLabel)))
             .addContainerGap())
     );

     cameraJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera"));

     originLabel.setText("Origin");

     originXLabel.setText("X");

     originXActualLabel.setText("jLabel3");

     originYLabel.setText("Y");

     originYActualLabel.setText("jLabel5");

     originZLabel.setText("Z");

     originZActualLabel.setText("jLabel5");

     directionLabel.setText("Direction");

     directionXLabel.setText("X");

     directionXActualLabel.setText("jLabel3");

     directionYLabel.setText("Y");

     directionYActualLabel.setText("jLabel5");

     directionZLabel.setText("Z");

     directionZActualLabel.setText("jLabel5");

     javax.swing.GroupLayout cameraJPanelLayout = new javax.swing.GroupLayout(cameraJPanel);
     cameraJPanel.setLayout(cameraJPanelLayout);
     cameraJPanelLayout.setHorizontalGroup(
         cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraJPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(directionLabel)
                 .addComponent(originLabel))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(cameraJPanelLayout.createSequentialGroup()
                     .addComponent(originXLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(originXActualLabel)
                     .addGap(18, 18, 18)
                     .addComponent(originYLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(originYActualLabel)
                     .addGap(18, 18, 18)
                     .addComponent(originZLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(originZActualLabel))
                 .addGroup(cameraJPanelLayout.createSequentialGroup()
                     .addComponent(directionXLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(directionXActualLabel)
                     .addGap(18, 18, 18)
                     .addComponent(directionYLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(directionYActualLabel)
                     .addGap(18, 18, 18)
                     .addComponent(directionZLabel)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(directionZActualLabel)))
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
     );
     cameraJPanelLayout.setVerticalGroup(
         cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraJPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originLabel)
                 .addComponent(originXLabel)
                 .addComponent(originXActualLabel)
                 .addComponent(originYLabel)
                 .addComponent(originYActualLabel)
                 .addComponent(originZLabel)
                 .addComponent(originZActualLabel))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(cameraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionLabel)
                 .addComponent(directionXLabel)
                 .addComponent(directionXActualLabel)
                 .addComponent(directionYLabel)
                 .addComponent(directionYActualLabel)
                 .addComponent(directionZLabel)
                 .addComponent(directionZActualLabel))
             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
     );

     cameraOriginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Move Camera Origin"));

     originAlongAxesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Along axes"));

     originYPlusButton.setText("+ Y");
     originYPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originYPlusButtonActionPerformed(evt);
         }
     });

     originZMinusButton.setText("- Z");
     originZMinusButton.setToolTipText("");
     originZMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originZMinusButtonActionPerformed(evt);
         }
     });

     originXMinusButton.setText("- X");
     originXMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originXMinusButtonActionPerformed(evt);
         }
     });

     originXPlusButton.setText("+ X");
     originXPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originXPlusButtonActionPerformed(evt);
         }
     });

     originZPlusButton.setText("+ Z");
     originZPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originZPlusButtonActionPerformed(evt);
         }
     });

     originYMinusButton.setText("- Y");
     originYMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originYMinusButtonActionPerformed(evt);
         }
     });

     javax.swing.GroupLayout originAlongAxesPanelLayout = new javax.swing.GroupLayout(originAlongAxesPanel);
     originAlongAxesPanel.setLayout(originAlongAxesPanelLayout);
     originAlongAxesPanelLayout.setHorizontalGroup(
         originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(originAlongAxesPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(originXMinusButton)
                 .addGroup(originAlongAxesPanelLayout.createSequentialGroup()
                     .addComponent(originZPlusButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(originAlongAxesPanelLayout.createSequentialGroup()
                             .addComponent(originYPlusButton)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                             .addComponent(originZMinusButton))
                         .addComponent(originYMinusButton)
                         .addGroup(originAlongAxesPanelLayout.createSequentialGroup()
                             .addGap(81, 81, 81)
                             .addComponent(originXPlusButton)))))
             .addContainerGap())
     );
     originAlongAxesPanelLayout.setVerticalGroup(
         originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(originAlongAxesPanelLayout.createSequentialGroup()
             .addGroup(originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originYPlusButton)
                 .addComponent(originZMinusButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originXMinusButton)
                 .addComponent(originXPlusButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(originAlongAxesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originZPlusButton)
                 .addComponent(originYMinusButton))
             .addContainerGap())
     );

     originAlongOrientationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Along orientation"));

     originUpButton.setText("Up");
     originUpButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originUpButtonActionPerformed(evt);
         }
     });

     originForwardButton.setText("Forward");
     originForwardButton.setToolTipText("");
     originForwardButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originForwardButtonActionPerformed(evt);
         }
     });

     originLeftButton.setText("Left");
     originLeftButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originLeftButtonActionPerformed(evt);
         }
     });

     originRightButton.setText("Right");
     originRightButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originRightButtonActionPerformed(evt);
         }
     });

     originBackButton.setText("Back");
     originBackButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originBackButtonActionPerformed(evt);
         }
     });

     originDownButton.setText("Down");
     originDownButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             originDownButtonActionPerformed(evt);
         }
     });

     javax.swing.GroupLayout originAlongOrientationPanelLayout = new javax.swing.GroupLayout(originAlongOrientationPanel);
     originAlongOrientationPanel.setLayout(originAlongOrientationPanelLayout);
     originAlongOrientationPanelLayout.setHorizontalGroup(
         originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(originAlongOrientationPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(originLeftButton)
                 .addGroup(originAlongOrientationPanelLayout.createSequentialGroup()
                     .addComponent(originBackButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(originAlongOrientationPanelLayout.createSequentialGroup()
                             .addComponent(originUpButton)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                             .addComponent(originForwardButton))
                         .addComponent(originDownButton)
                         .addGroup(originAlongOrientationPanelLayout.createSequentialGroup()
                             .addGap(81, 81, 81)
                             .addComponent(originRightButton)))))
             .addContainerGap())
     );
     originAlongOrientationPanelLayout.setVerticalGroup(
         originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(originAlongOrientationPanelLayout.createSequentialGroup()
             .addGroup(originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originUpButton)
                 .addComponent(originForwardButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originLeftButton)
                 .addComponent(originRightButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(originAlongOrientationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(originBackButton)
                 .addComponent(originDownButton))
             .addContainerGap())
     );

     javax.swing.GroupLayout cameraOriginPanelLayout = new javax.swing.GroupLayout(cameraOriginPanel);
     cameraOriginPanel.setLayout(cameraOriginPanelLayout);
     cameraOriginPanelLayout.setHorizontalGroup(
         cameraOriginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraOriginPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(cameraOriginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(originAlongAxesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(originAlongOrientationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
     );
     cameraOriginPanelLayout.setVerticalGroup(
         cameraOriginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraOriginPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(originAlongAxesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(originAlongOrientationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addContainerGap())
     );

     cameraDirectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Move Camera Direction"));

     jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Along axes"));

     directionYPlusButton.setText("+ Y");
     directionYPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionYPlusButtonActionPerformed(evt);
         }
     });

     directionZMinusButton.setText("- Z");
     directionZMinusButton.setToolTipText("");
     directionZMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionZMinusButtonActionPerformed(evt);
         }
     });

     directionXMinusButton.setText("- X");
     directionXMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionXMinusButtonActionPerformed(evt);
         }
     });

     directionXPlusButton.setText("+ X");
     directionXPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionXPlusButtonActionPerformed(evt);
         }
     });

     directionZPlusButton.setText("+ Z");
     directionZPlusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionZPlusButtonActionPerformed(evt);
         }
     });

     directionYMinusButton.setText("- Y");
     directionYMinusButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionYMinusButtonActionPerformed(evt);
         }
     });

     javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
     jPanel5.setLayout(jPanel5Layout);
     jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
             .addContainerGap()
             .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(directionXMinusButton)
                 .addGroup(jPanel5Layout.createSequentialGroup()
                     .addComponent(directionZPlusButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel5Layout.createSequentialGroup()
                             .addComponent(directionYPlusButton)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                             .addComponent(directionZMinusButton))
                         .addComponent(directionYMinusButton)
                         .addGroup(jPanel5Layout.createSequentialGroup()
                             .addGap(81, 81, 81)
                             .addComponent(directionXPlusButton)))))
             .addContainerGap())
     );
     jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
             .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionYPlusButton)
                 .addComponent(directionZMinusButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionXMinusButton)
                 .addComponent(directionXPlusButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionZPlusButton)
                 .addComponent(directionYMinusButton))
             .addContainerGap())
     );

     jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Along orientation"));

     directionUpButton.setText("Up");
     directionUpButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionUpButtonActionPerformed(evt);
         }
     });

     directionForwardButton.setText("Forward");
     directionForwardButton.setToolTipText("");
     directionForwardButton.setEnabled(false);
     directionForwardButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionForwardButtonActionPerformed(evt);
         }
     });

     directionLeftButton.setText("Left");
     directionLeftButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionLeftButtonActionPerformed(evt);
         }
     });

     directionRightButton.setText("Right");
     directionRightButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionRightButtonActionPerformed(evt);
         }
     });

     directionBackButton.setText("Back");
     directionBackButton.setEnabled(false);
     directionBackButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionBackButtonActionPerformed(evt);
         }
     });

     directionDownButton.setText("Down");
     directionDownButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
             directionDownButtonActionPerformed(evt);
         }
     });

     javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
     jPanel6.setLayout(jPanel6Layout);
     jPanel6Layout.setHorizontalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel6Layout.createSequentialGroup()
             .addContainerGap()
             .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(directionLeftButton)
                 .addGroup(jPanel6Layout.createSequentialGroup()
                     .addComponent(directionBackButton)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel6Layout.createSequentialGroup()
                             .addComponent(directionUpButton)
                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                             .addComponent(directionForwardButton))
                         .addComponent(directionDownButton)
                         .addGroup(jPanel6Layout.createSequentialGroup()
                             .addGap(81, 81, 81)
                             .addComponent(directionRightButton)))))
             .addContainerGap())
     );
     jPanel6Layout.setVerticalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel6Layout.createSequentialGroup()
             .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionUpButton)
                 .addComponent(directionForwardButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionLeftButton)
                 .addComponent(directionRightButton))
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(directionBackButton)
                 .addComponent(directionDownButton))
             .addContainerGap())
     );

     javax.swing.GroupLayout cameraDirectionPanelLayout = new javax.swing.GroupLayout(cameraDirectionPanel);
     cameraDirectionPanel.setLayout(cameraDirectionPanelLayout);
     cameraDirectionPanelLayout.setHorizontalGroup(
         cameraDirectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraDirectionPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addGroup(cameraDirectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
     );
     cameraDirectionPanelLayout.setVerticalGroup(
         cameraDirectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cameraDirectionPanelLayout.createSequentialGroup()
             .addContainerGap()
             .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addContainerGap())
     );

     javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
     getContentPane().setLayout(layout);
     layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addContainerGap()
             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addGroup(layout.createSequentialGroup()
                     .addComponent(cameraOriginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(cameraDirectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                 .addComponent(mouseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(cameraJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
     );
     layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addComponent(mouseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(cameraJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                 .addComponent(cameraOriginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(cameraDirectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addContainerGap())
     );

     pack();
   }// </editor-fold>//GEN-END:initComponents

   private void originYMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originYMinusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(0, -MOVEMENT_AMOUNT, 0);
   }//GEN-LAST:event_originYMinusButtonActionPerformed

   private void originZPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originZPlusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(0, 0, MOVEMENT_AMOUNT);
   }//GEN-LAST:event_originZPlusButtonActionPerformed

   private void originXPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originXPlusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(MOVEMENT_AMOUNT, 0, 0);
   }//GEN-LAST:event_originXPlusButtonActionPerformed

   private void originXMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originXMinusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(-MOVEMENT_AMOUNT, 0, 0);
   }//GEN-LAST:event_originXMinusButtonActionPerformed

   private void originZMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originZMinusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(0, 0, -MOVEMENT_AMOUNT);
   }//GEN-LAST:event_originZMinusButtonActionPerformed

   private void originYPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originYPlusButtonActionPerformed
      _traceManager.moveOriginAlongAxis(0, MOVEMENT_AMOUNT, 0);
   }//GEN-LAST:event_originYPlusButtonActionPerformed

   private void originUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originUpButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(0, MOVEMENT_AMOUNT, 0);
   }//GEN-LAST:event_originUpButtonActionPerformed

   private void originForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originForwardButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(0, 0, -MOVEMENT_AMOUNT);
   }//GEN-LAST:event_originForwardButtonActionPerformed

   private void originLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originLeftButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(-MOVEMENT_AMOUNT, 0, 0);
   }//GEN-LAST:event_originLeftButtonActionPerformed

   private void originRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originRightButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(MOVEMENT_AMOUNT, 0, 0);
   }//GEN-LAST:event_originRightButtonActionPerformed

   private void originBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originBackButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(0, 0, MOVEMENT_AMOUNT);
   }//GEN-LAST:event_originBackButtonActionPerformed

   private void originDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originDownButtonActionPerformed
      _traceManager.moveOriginAlongOrientation(0, -MOVEMENT_AMOUNT, 0);
   }//GEN-LAST:event_originDownButtonActionPerformed

   private void directionYPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionYPlusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(0, ROTATION_AMOUNT, 0);
   }//GEN-LAST:event_directionYPlusButtonActionPerformed

   private void directionZMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionZMinusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(0, 0, -ROTATION_AMOUNT);
   }//GEN-LAST:event_directionZMinusButtonActionPerformed

   private void directionXMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionXMinusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(-ROTATION_AMOUNT, 0, 0);
   }//GEN-LAST:event_directionXMinusButtonActionPerformed

   private void directionXPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionXPlusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(ROTATION_AMOUNT, 0, 0);
   }//GEN-LAST:event_directionXPlusButtonActionPerformed

   private void directionZPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionZPlusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(0, 0, ROTATION_AMOUNT);
   }//GEN-LAST:event_directionZPlusButtonActionPerformed

   private void directionYMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionYMinusButtonActionPerformed
      _traceManager.moveDirectionAlongAxis(0, -ROTATION_AMOUNT, 0);
   }//GEN-LAST:event_directionYMinusButtonActionPerformed

   private void directionUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionUpButtonActionPerformed
      _traceManager.moveDirectionAlongOrientation(ROTATION_AMOUNT, 0, 0);
   }//GEN-LAST:event_directionUpButtonActionPerformed

   private void directionForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionForwardButtonActionPerformed
     // TODO add your handling code here:
   }//GEN-LAST:event_directionForwardButtonActionPerformed

   private void directionLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionLeftButtonActionPerformed
      _traceManager.moveDirectionAlongOrientation(0, ROTATION_AMOUNT, 0);
   }//GEN-LAST:event_directionLeftButtonActionPerformed

   private void directionRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionRightButtonActionPerformed
      _traceManager.moveDirectionAlongOrientation(0, -ROTATION_AMOUNT, 0);
   }//GEN-LAST:event_directionRightButtonActionPerformed

   private void directionBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionBackButtonActionPerformed
     // TODO add your handling code here:
   }//GEN-LAST:event_directionBackButtonActionPerformed

   private void directionDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionDownButtonActionPerformed
      _traceManager.moveDirectionAlongOrientation(-ROTATION_AMOUNT, 0, 0);
   }//GEN-LAST:event_directionDownButtonActionPerformed

   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
     /* Set the Nimbus look and feel */
     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
      */
     try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
                 break;
             }
         }
     } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form */
     java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
             new InfoJFrame(null).setVisible(true);
         }
     });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel cameraDirectionPanel;
   private javax.swing.JPanel cameraJPanel;
   private javax.swing.JPanel cameraOriginPanel;
   private javax.swing.JButton directionBackButton;
   private javax.swing.JButton directionDownButton;
   private javax.swing.JButton directionForwardButton;
   private javax.swing.JLabel directionLabel;
   private javax.swing.JButton directionLeftButton;
   private javax.swing.JButton directionRightButton;
   private javax.swing.JButton directionUpButton;
   private javax.swing.JLabel directionXActualLabel;
   private javax.swing.JLabel directionXLabel;
   private javax.swing.JButton directionXMinusButton;
   private javax.swing.JButton directionXPlusButton;
   private javax.swing.JLabel directionYActualLabel;
   private javax.swing.JLabel directionYLabel;
   private javax.swing.JButton directionYMinusButton;
   private javax.swing.JButton directionYPlusButton;
   private javax.swing.JLabel directionZActualLabel;
   private javax.swing.JLabel directionZLabel;
   private javax.swing.JButton directionZMinusButton;
   private javax.swing.JButton directionZPlusButton;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JPanel mouseJPanel;
   private javax.swing.JPanel originAlongAxesPanel;
   private javax.swing.JPanel originAlongOrientationPanel;
   private javax.swing.JButton originBackButton;
   private javax.swing.JButton originDownButton;
   private javax.swing.JButton originForwardButton;
   private javax.swing.JLabel originLabel;
   private javax.swing.JButton originLeftButton;
   private javax.swing.JButton originRightButton;
   private javax.swing.JButton originUpButton;
   private javax.swing.JLabel originXActualLabel;
   private javax.swing.JLabel originXLabel;
   private javax.swing.JButton originXMinusButton;
   private javax.swing.JButton originXPlusButton;
   private javax.swing.JLabel originYActualLabel;
   private javax.swing.JLabel originYLabel;
   private javax.swing.JButton originYMinusButton;
   private javax.swing.JButton originYPlusButton;
   private javax.swing.JLabel originZActualLabel;
   private javax.swing.JLabel originZLabel;
   private javax.swing.JButton originZMinusButton;
   private javax.swing.JButton originZPlusButton;
   private javax.swing.JLabel sceneLabel;
   private javax.swing.JLabel sceneXActualLabel;
   private javax.swing.JLabel sceneXLabel;
   private javax.swing.JLabel sceneYActualLabel;
   private javax.swing.JLabel sceneYLabel;
   private javax.swing.JLabel sceneZActualLabel;
   private javax.swing.JLabel sceneZLabel;
   private javax.swing.JLabel screenLabel;
   private javax.swing.JLabel screenXActualLabel;
   private javax.swing.JLabel screenXLabel;
   private javax.swing.JLabel screenYActualLabel;
   private javax.swing.JLabel screenYLabel;
   // End of variables declaration//GEN-END:variables
}
